name: proxy
networks:
  proxy:
    name: proxy
services:
  haproxy:
    image: haproxy:lts
    deploy:
      restart_policy: # wait until any of the hubs generated the haproxy.cfg and copied it to the shared /volume
        condition: unless-stopped
    depends_on:
      - hub
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    ports:
      - 25:25
      - 587:587
      - 588:588
      - 8404:8404
    networks:
      - proxy
    volumes:
      - ./docker/volume/haproxy:/usr/local/etc/haproxy:ro
      - ./docker/volume/ssl:/ssl:ro

  hub:
    image: dockerreg.planck.security/securityhub-dev:latest
    deploy:
      mode: replicated
      replicas: ${REPLICAS}
      endpoint_mode: dnsrr
      restart_policy:
        condition: unless-stopped
    networks:
      - proxy
    environment:
      - replicas=${REPLICAS}
      - admin_addr=${ADMIN_ADDR}
      - hostname=${HOSTNAME}
      - relay_domains=${RELAY_DOMAINS}
      - nexthop=${NEXTHOP}
      - mynetworks=${MYNETWORKS}
      - smtp_archive=${SMTP_ARCHIVE}
      - loglevel=${LOGLEVEL}
    # healthcheck: # spams the log with "warning: haproxy read: EOF"
      # test: ["CMD", "nc", "-z", "127.0.0.1", "25"]
      # interval: 30s
      # timeout: 10s
      # retries: 5
    volumes:
      - ./docker/volume:/volume
